name: CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and build
        run: |
          yarn install
          yarn build
        env:
          CI: true
      - name: archive
        run: |
          zip -r helpfeel-devtools.zip dist
#        if: startsWith(github.ref, 'refs/tags/')
      - name: release
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: helpfeel-devtools.zip